### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by scottybo** [ChristianBielak/vue-pagebuilder#2]
It would be great to see a demo of the page builder, or even just some screenshots :)

**Comment by ChristianBielak** [comment]
Hey Scott,

you are absolutely right. I will publish a demo next week.

**Comment by Neophen** [comment]
Any news on this?

**Comment by billiemead** [comment]
Would also love to see a demo

**Comment by milojennings** [comment]
I'd like to see a demo as well.

**Comment by ChristianBielak** [comment]
Took a while :D but a demo is now online
